AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ListarURs

  Retrieves UR list from manejo DB.

Parameters:
  ManejoAppSubnetId:
    Type: String
  ManejoAppSecurityGroupId:
    Type: String
  ManejoDBHost:
    Type: String
  ManejoDBPwd: 
    Type: String
  ManejoDBUser: 
    Type: String

Resources:
  ListarURs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: ListarURs.lambda_handler
      Runtime: python3.9
      Timeout: 15
      Environment:
        Variables:
          MANEJO_DB_HOST: !Ref ManejoDBHost
          MANEJO_DB_USER: !Ref ManejoDBUser
          MANEJO_DB_PWD: !Ref ManejoDBPwd
      Architectures:
        - arm64
      VpcConfig:
        SecurityGroupIds:
          - !Ref ManejoAppSecurityGroupId
        SubnetIds:
          - !Ref ManejoAppSubnetId
